# Generated by Django 3.2.20 on 2023-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='followings',
        ),
    ]
