# Generated by Django 3.2.20 on 2023-08-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_following_user_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
    ]
